apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  name: default-limits
spec:
  limits:
  - max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 200m
      memory: 64Mi
    type: Pod
  - default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    max:
      cpu: "2"
      memory: 4Gi
    maxLimitRequestRatio:
      cpu: "10"
    min:
      cpu: 100m
      memory: 64Mi
    type: Container
