---
apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    namespace: monitoring
    name: kube-state-metrics
    labels:
      app: kube-state-metrics
  spec:
    replicas: 1
    template:
      metadata:
        namespace: monitoring
        labels:
          app: kube-state-metrics
      spec:
        containers:
        - name: kube-state-metrics
          image: gcr.io/google_containers/kube-state-metrics:v1.1.0
          imagePullPolicy: IfNotPresent
          Ports:
          - containerPort: 8080
        serviceAccount: kube-state-metrics
        serviceAccountName: kube-state-metrics
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8080'
    name: kube-state-metrics
    namespace: monitoring
    labels:
      app: kube-state-metrics
  spec:
    ports:
    - name: kube-state-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: kube-state-metrics
kind: List
metadata: {}
